// PWA Service Worker Registration and Install Prompt
export interface BeforeInstallPromptEvent extends Event {
  prompt: () => Promise<void>;
  userChoice: Promise<{ outcome: 'accepted' | 'dismissed' }>;
}

let deferredPrompt: BeforeInstallPromptEvent | null = null;

// Store the current build ID to detect changes
let currentBuildId: string | null = null;

async function checkForUpdates(): Promise<boolean> {
  try {
    const response = await fetch('/api/build-info', {
      cache: 'no-cache',
      headers: { 'Cache-Control': 'no-cache' }
    });
    
    if (!response.ok) return false;
    
    const buildInfo = await response.json();
    const serverBuildId = buildInfo.buildId;
    
    // First time checking - store the build ID
    if (currentBuildId === null) {
      currentBuildId = serverBuildId;
      console.log('[PWA] Current build:', currentBuildId);
      return false;
    }
    
    // Check if build ID has changed
    if (currentBuildId !== serverBuildId) {
      console.log(`[PWA] New build detected! ${currentBuildId} → ${serverBuildId}`);
      return true;
    }
    
    return false;
  } catch (error) {
    console.error('[PWA] Update check failed:', error);
    return false;
  }
}

export function registerServiceWorker() {
  // NEVER register service worker in development to avoid cache issues
  if (!import.meta.env.PROD) {
    console.log('[PWA] Service Worker disabled in development mode');
    return;
  }

  if ('serviceWorker' in navigator) {
    // Only use production SW (generated by Workbox at build time)
    const swUrl = '/sw.js';
    
    // Register immediately, not on load, to start caching ASAP
    navigator.serviceWorker
      .register(swUrl)
      .then((registration) => {
        console.log('[PWA] Service Worker registered:', registration.scope);
        
        // Automatic update checking - check every 5 minutes
        const CHECK_INTERVAL = 5 * 60 * 1000; // 5 minutes
        
        // Check for updates immediately on registration
        registration.update().catch(err => 
          console.warn('[PWA] Initial update check failed:', err)
        );
        
        setInterval(async () => {
          console.log('[PWA] Checking for updates...');
          
          // Check service worker for updates
          await registration.update();
          
          // Check build ID for updates
          const hasUpdate = await checkForUpdates();
          
          if (hasUpdate) {
            console.log('[PWA] Update available - reloading to apply...');
            // Don't manually delete caches - Workbox handles this via skipWaiting/clientsClaim
            // Force reload to get new version (new SW will activate and clean old caches automatically)
            window.location.reload();
          }
        }, CHECK_INTERVAL);
        
        // Also check build ID shortly after registration
        setTimeout(async () => {
          await checkForUpdates();
        }, 5000);
        
        // Reload page when new SW takes control (automatic, no user interaction)
        let refreshing = false;
        navigator.serviceWorker.addEventListener('controllerchange', () => {
          if (!refreshing) {
            refreshing = true;
            console.log('[PWA] New service worker activated, reloading page');
            window.location.reload();
          }
        });
      })
      .catch((error) => {
        console.error('[PWA] Service Worker registration failed:', error);
      });
  }
}

export function initInstallPrompt() {
  window.addEventListener('beforeinstallprompt', (e) => {
    console.log('[PWA] Install prompt available');
    e.preventDefault();
    deferredPrompt = e as BeforeInstallPromptEvent;
    
    // Dispatch custom event so UI can show install button
    window.dispatchEvent(new Event('pwa-install-available'));
  });

  window.addEventListener('appinstalled', () => {
    console.log('[PWA] App installed successfully');
    deferredPrompt = null;
  });
}

export async function showInstallPrompt(): Promise<boolean> {
  if (!deferredPrompt) {
    console.log('[PWA] No install prompt available');
    return false;
  }

  try {
    await deferredPrompt.prompt();
    const choiceResult = await deferredPrompt.userChoice;
    
    console.log('[PWA] User choice:', choiceResult.outcome);
    
    deferredPrompt = null;
    return choiceResult.outcome === 'accepted';
  } catch (error) {
    console.error('[PWA] Install prompt error:', error);
    return false;
  }
}

export function isInstallable(): boolean {
  return deferredPrompt !== null;
}

export function isInstalled(): boolean {
  // Check if running in standalone mode (installed PWA)
  return window.matchMedia('(display-mode: standalone)').matches ||
         (window.navigator as any).standalone === true;
}

export function isPWASupported(): boolean {
  return 'serviceWorker' in navigator && 'PushManager' in window;
}

// Request notification permission (for future push notifications)
export async function requestNotificationPermission(): Promise<boolean> {
  if (!('Notification' in window)) {
    console.log('[PWA] Notifications not supported');
    return false;
  }

  if (Notification.permission === 'granted') {
    return true;
  }

  if (Notification.permission !== 'denied') {
    const permission = await Notification.requestPermission();
    return permission === 'granted';
  }

  return false;
}
